server:
  servlet:
    context-path: /
    session:
      persistent: true
  port: 2021
  error:
    whitelabel:
      enabled: true

spring:
  devtools:
    add-properties: false
  banner:
    location: banner.txt
  profiles:
    active: dev
  jackson: 
    serialization: 
      fail-on-empty-beans: false
      indent-output: true

springdoc:
  version: 2.2.1
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  group-configs:
    - group: stores
      paths-to-match: /api/**
  cache:
    disabled: true